tasks:
  - title: 文献调研与笔记
    desc: 收集并阅读相关领域的核心论文，做笔记并整理参考文献。  

  - title: 论文大纲设计
    desc: 根据研究主题，拟定论文框架与章节逻辑，确定主要研究问题和贡献点。  

  - title: 数据与实验整理
    desc: 汇总已有实验结果，或进行补充实验，并清理数据以便后续撰写。  

  - title: 初稿撰写
    desc: 按照大纲完成初稿，重点保证逻辑完整性，而非文字润色。  

  - title: 修改与润色
    desc: 根据导师/合作者反馈，修改逻辑漏洞，润色语言，优化图表。  

  - title: 投递与准备答复
    desc: 准备 Cover Letter，检查格式要求，提交论文，并预演可能的审稿意见答复。  